import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { App, ConfigProvider } from "antd";
import theme from "../utils/themeConfig";
import { AuthProvider } from "@/providers/authProvider";
import { ClientProvider } from "@/providers/clientProvider";
import { ContactProvider } from "@/providers/contactProvider";
import { OpportunityProvider } from "@/providers/opportunityProvider";
import { PricingRequestProvider } from "@/providers/pricingRequestProvider";
import { ProposalProvider } from "@/providers/proposalProvider";
import { ContractProvider } from "@/providers/contractProvider";
import { ActivityProvider } from "@/providers/activityProvider";
import { NoteProvider } from "@/providers/noteProvider";
import { DocumentProvider } from "@/providers/documentProvider";
import { DashboardProvider } from "@/providers/dashboardProvider";
import { ReportProvider } from "@/providers/reportProvider";
import { AIProvider } from "@/providers/aiProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RocketSales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <App>
          <ConfigProvider theme={theme}>
            <AntdRegistry>
              <AuthProvider>
                <ClientProvider>
                  <ContactProvider>
                    <OpportunityProvider>
                      <PricingRequestProvider>
                        <ProposalProvider>
                          <ContractProvider>
                            <ActivityProvider>
                              <NoteProvider>
                                <DocumentProvider>
                                  <DashboardProvider>
                                    <ReportProvider>
                                      <AIProvider>{children}</AIProvider>
                                    </ReportProvider>
                                  </DashboardProvider>
                                </DocumentProvider>
                              </NoteProvider>
                            </ActivityProvider>
                          </ContractProvider>
                        </ProposalProvider>
                      </PricingRequestProvider>
                    </OpportunityProvider>
                  </ContactProvider>
                </ClientProvider>
              </AuthProvider>
            </AntdRegistry>
          </ConfigProvider>
        </App>
      </body>
    </html>
  );
}
