import jsPDF from "jspdf";

export interface PDFSection {
  type: "title" | "heading" | "subheading" | "paragraph" | "list" | "table" | "separator";
  content?: string;
  items?: string[];
  headers?: string[];
  rows?: string[][];
}

export interface PDFDocumentData {
  title: string;
  subtitle?: string;
  author?: string;
  date?: string;
  sections: PDFSection[];
}

const COLORS = {
  primary: [223, 109, 39] as [number, number, number],      // #DF6D27 Orange
  secondary: [107, 114, 128] as [number, number, number],   // Gray
  dark: [17, 24, 39] as [number, number, number],           // Dark
  light: [243, 244, 246] as [number, number, number],       // Light gray
  white: [255, 255, 255] as [number, number, number],
  accent: [239, 68, 68] as [number, number, number],        // Red accent
  tableHeader: [223, 109, 39] as [number, number, number],  // #DF6D27 Orange
  tableStripe: [253, 237, 224] as [number, number, number], // #DF6D27 at ~10% tint
};

const MARGINS = { left: 20, right: 20, top: 20, bottom: 25 };
const PAGE_WIDTH = 210; // A4 width in mm
const CONTENT_WIDTH = PAGE_WIDTH - MARGINS.left - MARGINS.right;

function addPageFooter(doc: jsPDF, pageNumber: number, totalPages: string | number) {
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.secondary);
  doc.text(
    `Page ${pageNumber} of ${totalPages}`,
    PAGE_WIDTH / 2,
    pageHeight - 10,
    { align: "center" }
  );
  doc.text(
    `Generated by RocketSales AI`,
    MARGINS.left,
    pageHeight - 10
  );
  doc.text(
    new Date().toLocaleDateString(),
    PAGE_WIDTH - MARGINS.right,
    pageHeight - 10,
    { align: "right" }
  );
}

function checkPageBreak(doc: jsPDF, y: number, requiredSpace: number): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + requiredSpace > pageHeight - MARGINS.bottom) {
    doc.addPage();
    return MARGINS.top;
  }
  return y;
}

export function generatePDF(data: PDFDocumentData): string {
  const doc = new jsPDF("p", "mm", "a4");
  let y = MARGINS.top;

  // === COVER / HEADER SECTION ===
  // Header background bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, PAGE_WIDTH, 45, "F");

  // Title
  doc.setTextColor(...COLORS.white);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(data.title, MARGINS.left, 22);

  // Subtitle
  if (data.subtitle) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(data.subtitle, MARGINS.left, 32);
  }

  // Date and author line
  doc.setFontSize(9);
  const metaLine = [
    data.author ? `Author: ${data.author}` : null,
    data.date ? `Date: ${data.date}` : `Date: ${new Date().toLocaleDateString()}`,
  ]
    .filter(Boolean)
    .join("  |  ");
  doc.text(metaLine, MARGINS.left, 40);

  y = 55;

  // === BODY SECTIONS ===
  for (const section of data.sections) {
    switch (section.type) {
      case "title": {
        y = checkPageBreak(doc, y, 16);
        doc.setTextColor(...COLORS.primary);
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.text(section.content || "", MARGINS.left, y);
        y += 10;
        // Underline
        doc.setDrawColor(...COLORS.primary);
        doc.setLineWidth(0.5);
        doc.line(MARGINS.left, y - 4, MARGINS.left + CONTENT_WIDTH, y - 4);
        y += 4;
        break;
      }

      case "heading": {
        y = checkPageBreak(doc, y, 14);
        doc.setTextColor(...COLORS.dark);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text(section.content || "", MARGINS.left, y);
        y += 8;
        break;
      }

      case "subheading": {
        y = checkPageBreak(doc, y, 12);
        doc.setTextColor(...COLORS.secondary);
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text(section.content || "", MARGINS.left, y);
        y += 7;
        break;
      }

      case "paragraph": {
        doc.setTextColor(...COLORS.dark);
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const lines = doc.splitTextToSize(section.content || "", CONTENT_WIDTH);
        const lineHeight = 5;
        const totalHeight = lines.length * lineHeight;
        y = checkPageBreak(doc, y, totalHeight);
        doc.text(lines, MARGINS.left, y);
        y += totalHeight + 4;
        break;
      }

      case "list": {
        if (section.items && section.items.length > 0) {
          doc.setTextColor(...COLORS.dark);
          doc.setFontSize(10);
          doc.setFont("helvetica", "normal");
          for (const item of section.items) {
            const itemLines = doc.splitTextToSize(item, CONTENT_WIDTH - 8);
            const itemHeight = itemLines.length * 5;
            y = checkPageBreak(doc, y, itemHeight);
            // Bullet
            doc.setFillColor(...COLORS.primary);
            doc.circle(MARGINS.left + 2, y - 1.5, 1, "F");
            doc.text(itemLines, MARGINS.left + 8, y);
            y += itemHeight + 2;
          }
          y += 3;
        }
        break;
      }

      case "table": {
        if (section.headers && section.rows) {
          const colCount = section.headers.length;
          const colWidth = CONTENT_WIDTH / colCount;
          const rowHeight = 8;

          // Check if we have enough space for at least header + 1 row
          y = checkPageBreak(doc, y, rowHeight * 2 + 4);

          // Table header
          doc.setFillColor(...COLORS.tableHeader);
          doc.rect(MARGINS.left, y - 5, CONTENT_WIDTH, rowHeight, "F");
          doc.setTextColor(...COLORS.white);
          doc.setFontSize(9);
          doc.setFont("helvetica", "bold");
          section.headers.forEach((header, i) => {
            doc.text(header, MARGINS.left + i * colWidth + 2, y);
          });
          y += rowHeight;

          // Table rows
          doc.setFont("helvetica", "normal");
          section.rows.forEach((row, rowIndex) => {
            y = checkPageBreak(doc, y, rowHeight);
            // Alternate row background
            if (rowIndex % 2 === 0) {
              doc.setFillColor(...COLORS.tableStripe);
              doc.rect(MARGINS.left, y - 5, CONTENT_WIDTH, rowHeight, "F");
            }
            doc.setTextColor(...COLORS.dark);
            doc.setFontSize(9);
            row.forEach((cell, i) => {
              const cellText = doc.splitTextToSize(cell, colWidth - 4);
              doc.text(cellText[0] || "", MARGINS.left + i * colWidth + 2, y);
            });
            y += rowHeight;
          });
          y += 5;
        }
        break;
      }

      case "separator": {
        y = checkPageBreak(doc, y, 8);
        doc.setDrawColor(...COLORS.light);
        doc.setLineWidth(0.3);
        doc.line(MARGINS.left, y, MARGINS.left + CONTENT_WIDTH, y);
        y += 8;
        break;
      }
    }
  }

  // Add page numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addPageFooter(doc, i, totalPages);
  }

  // Return as base64 data URI
  return doc.output("datauristring");
}

export function downloadPDF(dataUri: string, filename: string) {
  const link = document.createElement("a");
  link.href = dataUri;
  link.download = filename.endsWith(".pdf") ? filename : `${filename}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}